### PR TITLE
Chore/shutdown rollups 0.7.0 dapps

### PR DESCRIPTION
**Pull request by endersonmaia**
I'm assuming that those DApps are not in use, since they're using an old version of rollups.

If this PR is approved, the DApps will be removed from Cartesi's Infrastructure.

### CODE REVIEW

**Comment by claudioantonio** [comment]
Are these DApps also deployed using newer Rollups releases?
For example, is the locus-biometrics@goerli also deployed using Rollups 0.8?

**Comment by endersonmaia** [comment]
> Are these DApps also deployed using newer Rollups releases? For example, is the locus-biometrics@goerli also deployed using Rollups 0.8?

No.

**Comment by tuler** [comment]
These are the showcase dapps that are currently running on the infrastructure

https://rolluplab.io/cartesian-battleship/
https://rolluplab.io/ballaum-worldcup-betting-dapp/
https://rolluplab.io/biometrics-classifier/
https://rolluplab.io/iris-classifier/
https://rolluplab.io/parking-dapp/
https://rolluplab.io/titanic-survivor/

**Comment by endersonmaia** [comment]
@tuler so I removed the ones mentioned from the list I'm proposing to remove in this PR.

**Review by tuler — APPROVED** [review]

**Pull request merged**
