### PR TITLE
feat: add voting DApp

### PR DESCRIPTION
**Pull request by Sotatek-ManhNguyen3**

### CODE REVIEW

**Review by endersonmaia — CHANGES_REQUESTED** [review]
Hey @Sotatek-ManhNguyen3 please change the target banch to `develop`.

Also, adjust the commit message to something like: `feat: add voting DApp`

**Comment by endersonmaia** [comment]
Hi @Sotatek-ManhNguyen3 , when trying to deploy a validator node in our infra, we're getting errors about the `sender`.

Please, look at this message from another PR https://github.com/cartesi/rollups-deployment/pull/1#issuecomment-1263927937

You'll find some information about how to fix this during the deployment of the contract.

/cc @tuler

**Comment by tuler** [comment]
@Sotatek-ManhNguyen3 please squash commits to a single `feat: add voting DApp`

**Comment by Sotatek-ManhNguyen3** [comment]
@tuler Updated!

**Pull request merged**
