### PR TITLE
aetheras-dinders DApps

### PR DESCRIPTION
**Pull request by endersonmaia**

### CODE REVIEW

**Comment by endersonmaia** [comment]
@maxabcr2000 I see all these DApps were built based on rollups-0.7.0, right ?

I'll remove the `optimism-goerli` one, and deploy the others, so we can merge this already.

Feel free to build the DApps again using the rollups-0.8.x release, and open a new PR for that.

Starting from rollups-0.8.0, the `optimism-goerli` should work.

**Review by endersonmaia — COMMENTED** [review]
DApps deployed.

@maxabcr2000 please test the `/inspect` and `/graphql` endpoints.

**goerli**

- `https://0xbe24cf307ad04e38378a37b8e9716f43c8dea159.goerli.rollups.staging.cartesi.io`
- `https://aetheras-dinder.goerli.rollups.staging.cartesi.io`

**arbitrum-goerli**

- `https://0xfcacb0cc2569c6680a213fe72c7b0ab0ea4aba7f.arbitrum-goerli.rollups.staging.cartesi.io`
- `https://aetheras-dinder.arbitrum-goerli.rollups.staging.cartesi.io`

**chiado**

- `https://0xbb89138717a377b99bf4f54afa3f4abfd0b74443.chiado.rollups.staging.cartesi.io`
- `https://aetheras-dinder.chiado.rollups.staging.cartesi.io`

**Review by tuler — APPROVED** [review]

**Comment by maxabcr2000** [comment]
> @maxabcr2000 I see all these DApps were built based on rollups-0.7.0, right ?
> 
> I'll remove the `optimism-goerli` one, and deploy the others, so we can merge this already.
> 
> Feel free to build the DApps again using the rollups-0.8.x release, and open a new PR for that.
> 
> Starting from rollups-0.8.0, the `optimism-goerli` should work.

I remember that all the DApps have been rebuilt using rollups-v0.8.1 in the previous PR already
Did you see any logs that indicated that the Dapp is still using rollups-0.7.0?

**Comment by maxabcr2000** [comment]
@endersonmaia 
I just opened a new [PR](https://github.com/cartesi/rollups-deployment/pull/24) for `optimism-goerli`, please help to review it.

**Comment by endersonmaia** [comment]
> @endersonmaia I remember that all the DApps have been rebuilt using rollups-v0.8.1 in the previous PR already Did you see any logs that indicated that the Dapp is still using rollups-0.7.0?

I somehow deployed the wrong image, `gcr.io/aetheras-io/dinder-cartesi:v0.2.0` instead of `gcr.io/aetheras-io/dinder-cartesi:v0.2.1`.

Just fixed that, please, if possible, test it all again and sorry for the noise. :)

**Pull request merged**
