### PR TITLE
feat: add aetheras-dinder dapp for arbitrum-goerli, optimism-goerli, goerli, and gnosis-chiado

### PR DESCRIPTION
**Pull request by maxabcr2000**
# Brief
Adding the dinder-cartesi DApp to be accepted in the infrastructure.

# Main Activities
Added .yaml file as requested in the documentation.

### CODE REVIEW

**Comment by maxabcr2000** [comment]
Hi, We've add a new yml file for `arbitrum-goerli` testnet please help to deploy a node with `1 block confirmation time`.

**Review by endersonmaia — CHANGES_REQUESTED** [review]
Please, adjust the directory hierarchy/naming from `./aetheras/dinder/` to `aetheras-dinder/`.

**Comment by maxabcr2000** [comment]
> Please, adjust the directory hierarchy/naming from `./aetheras/dinder/` to `aetheras-dinder/`.

Thanks for the information, fixed in [3591783](https://github.com/cartesi/rollups-deployment/pull/12/commits/3591783ae130e116d81b10b4ffad5533f9c12df3)

**Review by endersonmaia — CHANGES_REQUESTED** [review]
Please, keep just 3 commits in the PR, one per DApp.

**Comment by endersonmaia** [comment]
Also, I'm waiting for the CI to run over this, so we can make a final verification.

/cc @tuler

**Comment by maxabcr2000** [comment]
> Please, keep just 3 commits in the PR, one per DApp.

Hi, does this means that I should create three PR for each of yml file(or dapp)?

**Comment by tuler** [comment]
@maxabcr2000 can you rewrite the git history to have a single commit per network following conventional commit.
The message can be like `feat: add <name_of_your_dapp>@<network> DApp`

you can have a single PR for several networks, following the rule above

Thanks in advance

**Comment by endersonmaia** [comment]
> > Please, keep just 3 commits in the PR, one per DApp.
> 
> Hi, does this means that I should create three PR for each yml file(or dapp)?

No. Keep this PR, but with just 3 commits, one commit for each dapp.

**Review by endersonmaia — CHANGES_REQUESTED** [review]
I've deployed the DApp backend for `goerli` and `arbitrum-goerli`, the optimism doesn't support EIP-1559 for this `rollups-0.7.x` release.

Please, give it a try on the `/graphsql` and `/inspect` paths for the following URLs.

**goerli**

- `https://0xbe24cf307ad04e38378a37b8e9716f43c8dea159.goerli.rollups.staging.cartesi.io`
- `https://aetheras-dinder.goerli.rollups.staging.cartesi.io`

**arbitrum-goerli**

- `https://0xfcacb0cc2569c6680a213fe72c7b0ab0ea4aba7f.arbitrum-goerli.rollups.staging.cartesi.io`
- `https://aetheras-dinder.arbitrum-goerli.rollups.staging.cartesi.io`

---

So, I'll ask you to remove the `optimism-goerli` commit from the PR.

**Comment by maxabcr2000** [comment]
> * https://0xfcacb0cc2569c6680a213fe72c7b0ab0ea4aba7f.arbitrum-goerli.rollups.staging.cartesi.io

I've tried the urls by browser, url's for `goerli` works well, but `arbitrum-goerli` urls will get "502 Bad Gateway"

**Comment by endersonmaia** [comment]
> @claudio.silva has mentioned that there will be a rollups 0.8, which supports non EIP-1559 transactions this week, shall I just wait for the release, rebuild dapp and update `optimism-goerli` in this PR ?

You could update everything to the new rollups-0.8.1, and update this PR.

**Comment by miltonjonat** [comment]
@maxabcr2000 the new release also supports the Gnosis Chiado testnet! If you wish, you may add it to this PR along with Optimism Goerli, ok?

**Comment by maxabcr2000** [comment]
> @maxabcr2000 the new release also directly supports deploying to the Gnosis Chiado testnet! If you wish, you may add it to this PR along with Optimism Goerli, ok?

Sure do, thanks for the information!
Besides, do you know the websocket endpoint of `Gnosis Chiado` testnet? Is it something like `wss://rpc.chiadochain.net/wss`?

**Comment by maxabcr2000** [comment]
> > @maxabcr2000 the new release also directly supports deploying to the Gnosis Chiado testnet! If you wish, you may add it to this PR along with Optimism Goerli, ok?
> 
> Sure do, thanks for the information! Besides, do you know the websocket endpoint of `Gnosis Chiado` testnet? Is it something like `wss://rpc.chiadochain.net/wss`?

I've tested the url `wss://rpc.chiadochain.net/wss` to start a node on local and it worked!

**Comment by miltonjonat** [comment]
> I've tested the url `wss://rpc.chiadochain.net/wss` to start a node on local and it worked!

You're right! I've also noticed that their documentation on https://docs.gnosischain.com/tools/rpc strangely does not list the websocket endpoint for testnet. But the above URL, following the pattern of the mainnet endpoint, does seem to work normally!

**Comment by miltonjonat** [comment]
I've created an issue in their documentation repo to ask them to officially add a WS RPC endpoint in their docs.
https://github.com/gnosischain/documentation/issues/316

**Comment by tuler** [comment]
@maxabcr2000 the chiado network should be actually called `chiado` and not `gnosis_chiado`. We will probably change out infrastructure downstream to be `chiado` as well.
Meanwhile please try to rename the file to `chiado`

**Comment by maxabcr2000** [comment]
Fixed in 0f4aebd

**Comment by endersonmaia** [comment]
I messed the history during a rebase, will fix this here ([#21](https://github.com/cartesi/rollups-deployment/pull/21)) and close this PR.

Will also try to handle the CI for chiado.

**Comment by miltonjonat** [comment]
> I've created an issue in their documentation repo to ask them to officially add a WS RPC endpoint in their docs. [gnosischain/documentation#316](https://github.com/gnosischain/documentation/issues/316)

@maxabcr2000 and guys, they have now updated their docs, so that WS RPC we are using is indeed official 👍 
https://github.com/gnosischain/documentation/issues/316#issuecomment-1348690059

**Pull request closed without merging**
