### PR TITLE
Calculator Deployment

### PR DESCRIPTION
**Pull request by souzavinny**
## Brief
The first Atempt to use the Cartesi infrastructure for Calculator DApp.

## Main activities
Following the [Cartesi Instructions](https://github.com/cartesi/rollups-deployment)

### CODE REVIEW

**Comment by endersonmaia** [comment]
Hey @souzavinny , could you please rename `goerli.yml` to `goerli.yaml` (`s/yml/yaml/`) ?

Our CI expects a `*.yaml` file.

**Comment by endersonmaia** [comment]
I see the instructions mentions `.yml`, we should fix it or the CI (or both).

**Review by endersonmaia — CHANGES_REQUESTED** [review]
rename `calculator/goerli.yml` to `calculator/goerli.yaml`

**Comment by souzavinny** [comment]
Done changing the file extesion.

**Comment by endersonmaia** [comment]
@souzavinny could you rebase and squash in a single commit ?

and keep the commit message format https://www.conventionalcommits.org/en/v1.0.0/#summary

sugestion: `feat: add calculator@goerli DApp`

**Comment by souzavinny** [comment]
@endersonmaia  Rebased and squashed

**Comment by tuler** [comment]
@souzavinny can you please rebase your branch to the develop branch and force push?

**Comment by souzavinny** [comment]
Rebased to develop and pushed @tuler

**Review by endersonmaia — APPROVED** [review]
LGTM

The DApp backend (`/inspect` and `/graphql` paths) is accessible from those endpoints:

- https://calculator.goerli.rollups.staging.cartesi.io/
- https://0xb5f080582c3615dc2c77e876a822a76e2556ea4f.goerli.rollups.staging.cartesi.io/

The CI is complaining about different machine hashes from container image and contract.

https://github.com/cartesi/rollups-deployment/actions/runs/3154246407/jobs/5131658553

**Comment by souzavinny** [comment]
Hey there @tuler ,
Done this change and left the history the same as before. 
Cheers,

**Comment by souzavinny** [comment]
> LGTM
> 
> The DApp backend (`/inspect` and `/graphql` paths) is accessible from those endpoints:
> 
> * https://calculator.goerli.rollups.staging.cartesi.io/
> * https://0xb5f080582c3615dc2c77e876a822a76e2556ea4f.goerli.rollups.staging.cartesi.io/
> 
> The CI is complaining about different machine hashes from container image and contract.
> 
> https://github.com/cartesi/rollups-deployment/actions/runs/3154246407/jobs/5131658553

This case is because the contract was deployed a while ago, and the machine container was created when I started this procedure (They both use the exact backend code, but they will sure differ in hashes).
This is a problem?

**Comment by tuler** [comment]
This will be a problem in future versions.
It's important that the build of the machine is reproducible, meaning that every time you rebuild the machine it produces the same hash. This simplifies the deployment procedure, but can be tricky in practice.

**Comment by souzavinny** [comment]
> This will be a problem in future versions. It's important that the build of the machine is reproducible, meaning that every time you rebuild the machine it produces the same hash. This simplifies the deployment procedure, but can be tricky in practice.

Understood. 
I asked because I will be doing the m2cgen and knn PRs, and the contract address of those are already on. That said I have to deploy them again in testnet, right?

Also, I've tested the backend infrastructure with my front end now and seems to be everything ok.
Thanks!

**Comment by tuler** [comment]
Yes, do some tests of reproducibility, build once, check hash. Clean cache and build again, and compare.
Then you deploy to testnet.

**Comment by endersonmaia** [comment]
@souzavinny the backend was redeployed, you should update the endpoint urls from `https://calculator.goerli.rollups.staging.cartesi.io/` to `https://locus-calculator.goerli.rollups.staging.cartesi.io/`.

The one that uses the `contractAddress` keeps the same, since it had no changes.

**Comment by souzavinny** [comment]
Ok, Thank you @endersonmaia .

**Comment by tuler** [comment]
@souzavinny we found another issue in the process.
The deployed dapp must use the Cartesi public address as the validator of the application, when you deploy the contract.
As you were running your own node, with your own wallet, you probably deployed the contract with that same wallet, and by default the validator is set to be the deployer.
But this is not a requirement, you can deploy a dapp, and choose some other address to be the validator.
You probably deployed using the `deploy-testnet.yml` from the example repo? It executes the `cartesi/rollups-cli` image:

```
$ docker run cartesi/rollups-cli:0.6.0 create --help
Instantiate rollups application

Options:
      --version           Show version number                          [boolean]
      --rpc               JSON-RPC URL                       [string] [required]
      --mnemonic          Wallet mnemonic                    [string] [required]
      --accountIndex      Account index from mnemonic      [number] [default: 0]
      --deploymentFile    Contracts deployment file                     [string]
      --diamondOwner      Rollups contract owner                        [string]
      --templateHash      Cartesi Machine template hash                 [string]
      --templateHashFile  Cartesi Machine template hash file            [string]
      --inputDuration     Time window of input collection, in seconds
                                                       [number] [default: 86400]
      --challengePeriod   Time window of challenge, in seconds
                                                      [number] [default: 604800]
      --inputLog2Size     Log2 size of input              [number] [default: 25]
      --feePerClaim       Fee to reward validators for claims
                                      [string] [default: "10000000000000000000"]
      --feeManagerOwner   Fee Manager owner, defaults to the address of the depl
                          oyer                                          [string]
      --validators        Comma separated list of validator nodes addresses. If
                          item is a number consider as an account index of the d
                          efined MNEMONIC                [string] [default: "0"]
      --outputFile        Output file to write application address      [string]
      --config            Path to JSON config file
  -h, --help              Show help                                    [boolean]
```

You need a change to use:
```
--validators 0x18930e8a66a1DbE21D00581216789AAB7460Afd0
```

Which is our wallet public address, which is validating all dapps deployed to our infrastructure.
Let us know if you need further help.

**Comment by tuler** [comment]
> That said, I will have to re-deploy all dapps again with this flag "--validators 0x18930e8a66a1DbE21D00581216789AAB7460Afd0", right?

Correct

**Comment by tuler** [comment]
If you rebase again to develop branch, now there is a check for that, so we can catch it earlier in the process.

**Comment by endersonmaia** [comment]
@souzavinny I just redeployed the validator node for this DApp based on the last commito [afbc6a](https://github.com/cartesi/rollups-deployment/commit/afbc6a6820accf0e6d548ec90c47e37425e0e3df)

**Comment by endersonmaia** [comment]
@tuler merge if you think we can move forward with the machine hashes this way.

**Pull request merged**
