### PR TITLE
iot rollups dapp 0.6

### PR DESCRIPTION
**Pull request by ArtV97**

### CODE REVIEW

**Comment by tuler** [comment]
I force pushed your branch with a rebased version from develop

**Comment by ArtV97** [comment]
Done @endersonmaia

**Review by endersonmaia — CHANGES_REQUESTED** [review]
Could you rename the directory to `uff-iot` ?

We'll use the name of the directory as input for the URL definition.

**Comment by ArtV97** [comment]
@endersonmaia , sure. Here it is.

**Review by endersonmaia — APPROVED** [review]
The DApp backend (/inspect and /graphql paths) is accessible from those endpoints:

https://uff-iot.goerli.rollups.staging.cartesi.io/
https://0x376a07505577440713f27576bb93efc24ca92c34.goerli.rollups.staging.cartesi.io/

/cc @tuler

**Comment by tuler** [comment]
@ArtV97 can you rewrite the git history to have a single commit following conventional commit.
The message can be like `feat: add <name_of_your_dapp>@<network> DApp`

Thanks in advance

**Comment by ArtV97** [comment]
Hello @tuler, I just did it.

**Pull request merged**
