### PR TITLE
feat: Add locus-biometrics@goerli DApp

### PR DESCRIPTION
**Pull request by souzavinny**
## Brief 
Adds the biometrics DApp to cartesi infrastructure.

## Main activities
Add the requested information in the yaml file.

### CODE REVIEW

**Comment by endersonmaia** [comment]
@souzavinny we had to work on a fix for the validator-node to work with the biometrics DApp, but during tests, I found the following error from `server-manager` logs:

```
...
Received CheckIn for session default_rollups_id
  Check-in for session default_rollups_id passed with address localhost:35697
    Clearing buffers
      clearing rx buffer
      clearing input metadata
      clearing voucher hashes
      clearing notice hashes
    Writing rx buffer
    Writing input metadata
    Resetting iflags_Y
  Running advance/inspect state increment 0
[INFO  rollup_http_server::http_service] Received new request of type ADVANCE
[INFO  rollup_http_server::rollup] read zero size payload from advance state request
[INFO  actix_web::middleware::logger] 127.0.0.1 "POST /finish HTTP/1.1" 200 205 "-" "python-requests/2.27.1" 0.001935
INFO:__main__:Received finish status 200
ERROR:__main__:Error processing data {'metadata': {'msg_sender': '0x5c13fdd272ea850052d4011c5c3600f466c67985', 'epoch_index': 0, 'input_index': 0, 'block_number': 7729647, 'timestamp': 1665174240}, 'payload': '0
Traceback (most recent call last):
  File "/mnt/dapp/biometrics.py", line 93, in handle_advance
    input_json = json.loads(input)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  Running advance/inspect state increment 1
    Reading report 0
      Reading report length
      Reading report payload of length 605
  Running advance/inspect state increment 0
[INFO  actix_web::middleware::logger] 127.0.0.1 "POST /report HTTP/1.1" 202 0 "-" "python-requests/2.27.1" 0.001748
INFO:__main__:Received report status 202 body b''
INFO:__main__:Sending finish
  Running advance/inspect state increment 1
    Input skipped because machine requested
  Skipped input 0
    Rolling back
  Triggering machine server check-in
  Waiting check-in
Received CheckIn for session default_rollups_id
  Check-in for session default_rollups_id passed with address localhost:37571
Received GetSessionStatus for session default_rollups_id
  0
Received GetEpochStatus for session default_rollups_id epoch 0
Received GetSessionStatus for session default_rollups_id
  0
Received GetEpochStatus for session default_rollups_id epoch 0
Received FinishEpoch for session default_rollups_id epoch 0
Received GetSessionStatus for session default_rollups_id
  0
  1
...
```

**Comment by endersonmaia** [comment]
Even with this error, the validator-node is still UP.



The DApp backend (/inspect and /graphql paths) is accessible from those endpoints:

- https://locus-biometrics.goerli.rollups.staging.cartesi.io/inspect
- https://0x5c13fdd272ea850052d4011c5c3600f466c67985.goerli.rollups.staging.cartesi.io/graphql

/cc @tuler

**Comment by endersonmaia** [comment]
@souzavinny we have a new server-manager [1] release with the fix I've mentioned , could you build the image again and send a fixup pointing to the new images ?

1. : [cartesi/server-manager:0.4.2](https://hub.docker.com/layers/cartesi/server-manager/0.4.2/images/sha256-5a1b318c4999b349179c414854d2a9f1468ce48e0571c5583c5232b4986690a2?context=explore)

**Comment by tuler** [comment]
For the hashes to always match the build of the application must be [reproducible](https://reproducible-builds.org).

This depends on how the application is built, and sometimes may not be too easy to do.

As an example, we are currently investigating how to build python applications in a reproducible way, which may be tricky.

Is the source code of your dapp public?

**Comment by souzavinny** [comment]
> For the hashes to always match the build of the application must be [reproducible](https://reproducible-builds.org).
> 
> This depends on how the application is built, and sometimes may not be too easy to do.
> 
> As an example, we are currently investigating how to build python applications in a reproducible way, which may be tricky.
> 
> Is the source code of your dapp public?

Hey Danilo how is it going? 
Here is the source of the current biometrics: https://github.com/souzavinny/rollups-examples/blob/hotfix/biometrics-payload-adjustment/biometrics/biometrics.py
About python applications: I guess that is because some things in python use timestamps when you build the applications. Lyno suggested me to do some cleaning steps in the python cache when deploying to see if it works.

**Comment by tuler** [comment]
Yes, I see you don’t use python crossenv, which also have a problem with being reproducible, so deleting or not generating puçá he should help.

**Comment by claudioantonio** [comment]
> ...so deleting or not generating puçá he should help.

@tuler your comment has a typo.

**Comment by souzavinny** [comment]
> Yes, I see you don’t use python crossenv, which also have a problem with being reproducible, so deleting or not generating pycache should help.

Thanks, I will try again to see what happens.

**Comment by endersonmaia** [comment]
> Hey @endersonmaia , how is it going? I've changed everything needed for the biometrics dapp in this update. Somehow, the hash divergence still happens even though I'm doing exactly the same steps for all the other dapps. Do you have any hint why this happens? cheers,

Like others said already, making the hash matches is hard some time, but we won't block , and the DApp backend is deployed.

**Comment by endersonmaia** [comment]
@souzavinny the `docker.io/marcussouza90/marcus-repo:biometrics` image is still based on the `server-manager:0.4.0`, could you build it again using `server-manager:0.4.2` ?

```
❯ docker container run -ti --rm docker.io/marcussouza90/marcus-repo:biometrics
manager version is 0.4.0
```

**Comment by souzavinny** [comment]
It seems the goerli testnet is having some issues in deploying dapps (Since I'm using the new manager now I imagine I have to deploy again for a new contract and then push the new container to the docker hub).

**Review by endersonmaia — APPROVED** [review]
LGTM :rocket: 

The DApp backend (/inspect and /graphql paths) is accessible from those endpoints:

- `https://locus-biometrics.goerli.rollups.staging.cartesi.io/`
- `https://0xaf5b1ad8672d3b034f28057e0673a6115bca4f84.goerli.rollups.staging.cartesi.io/`

/cc @tuler

**Comment by souzavinny** [comment]
Hey there everyone,
The biometrics backend had some adjustments as requested by the cartesi tech team. The new version is ready do be deployed. Thank you kindly,
Cheers,

**Comment by souzavinny** [comment]
I also have a question @endersonmaia  @tuler : I have successfully deployed the same biometrics in the arbitrum-goerli chain. To use the cartesi infrastructure, I have to update this PR with another file named arbitrum-goerli.yaml? Or I have to create another PR with just the new yaml file?
Cheers,

**Comment by endersonmaia** [comment]
> I also have a question @endersonmaia @tuler : I have successfully deployed the same biometrics in the arbitrum-goerli chain. To use the cartesi infrastructure, I have to update this PR with another file named arbitrum-goerli.yaml? Or I have to create another PR with just the new yaml file? Cheers,

You can send on this PR, just send on a another commit.

**Comment by souzavinny** [comment]
> > I also have a question @endersonmaia @tuler : I have successfully deployed the same biometrics in the arbitrum-goerli chain. To use the cartesi infrastructure, I have to update this PR with another file named arbitrum-goerli.yaml? Or I have to create another PR with just the new yaml file? Cheers,
> 
> You can send on this PR, just send on a another commit.

Thanks! Added another file and commit about the arbitrum.

**Comment by endersonmaia** [comment]
@souzavinny please, give it a try on the `/graphsql` and `/inspect` paths for the following URLs.

**Ethereum Goerli**

- `https://0x5a541ece563b56a8700ff52875f688c1719b6ed9.goerli.rollups.staging.cartesi.io`
- `https://locus-biometrics.goerli.rollups.staging.cartesi.io`

**Arbitrum Goerli**

- `https://0x0304a8b0f6e4fd8d40180a4465df36451f321baa.arbitrum-goerli.rollups.staging.cartesi.io`
- `https://locus-biometrics.arbitrum-goerli.rollups.staging.cartesi.io`

**Comment by souzavinny** [comment]
Hey @endersonmaia ,
Could you update the biometrics again? I was in touch with Lyno and we had some issues to deal with. We had some doubts about the validators being the same for the two chains deployed. But if need to change that I can do another deploy. 
Cheers,

**Comment by endersonmaia** [comment]
@souzavinny please, give it a try on the /graphsql and /inspect paths for the following URLs.

**Ethereum Goerli**

- `0x891ea0ad1868183c99103ad779735ac7c0deff3e.goerli.rollups.staging.cartesi.io`
- `locus-biometrics.goerli.rollups.staging.cartesi.io`

**Arbitrum Goerli**

- `0xbb10f7ef8a1464e6ae1e2fb95b7b80648fcb6e92.arbitrum-goerli.rollups.staging.cartesi.io`
- `locus-biometrics.arbitrum-goerli.rollups.staging.cartesi.io`

**Comment by souzavinny** [comment]
Hey @endersonmaia ,
The last version of biometrics went with a bug in riscv. Could you update the biometrics again? For some reason I don't know the hashes now are good as well. Thank you kindly,
Cheers,

**Comment by endersonmaia** [comment]
@souzavinny could you keep he changes made to the goerli.yaml on the first commit

**Comment by souzavinny** [comment]
> 

You mean, only one commit ?

**Comment by endersonmaia** [comment]
> > 
> 
> You mean, only one commit ?(rebase and squash)

I mean two commit, on for each Dapp.

If you see the commit https://github.com/cartesi/rollups-deployment/pull/6/commits/bffa96567debda741235d522a2ed59a123a45532, it has a change to the goerli.yaml. This change should be on the first commit.

Got it ?

**Comment by souzavinny** [comment]
> > > 
> > 
> > 
> > You mean, only one commit ?(rebase and squash)
> 
> I mean two commits, one for each DApp@network.
> 
> If you see the commit [bffa965](https://github.com/cartesi/rollups-deployment/commit/bffa96567debda741235d522a2ed59a123a45532), it has a change to the goerli.yaml. This change should be on the first commit.
> 
> Got it ?

OK, I will be doing this now.

**Comment by souzavinny** [comment]
> 

Done the commit organization. Thanks!

**Comment by endersonmaia** [comment]
**Goerli**

- `0x208976fa22017ab98181d2d2f8a23cc7c9d04ec1.goerli.rollups.staging.cartesi.io`
- `locus-biometrics.goerli.rollups.staging.cartesi.io`

**Arbitrum Goerli**

- `0xbe4d6cb7ea918da6cf0e22ce63352a43316252e8.arbitrum-goerli.rollups.staging.cartesi.io`
- `locus-biometrics.arbitrum-goerli.rollups.staging.cartesi.io`

**Pull request merged**
