### PR TITLE
feat: solana-twitter

### PR DESCRIPTION
**Pull request by fabiooshiro**

### CODE REVIEW

**Comment by fabiooshiro** [comment]
Instructions from Lyno:

Hey @fabio.oshiro 
To deploy using the  rollups-deployment project you should add the validators when you are deploying the contracts, which is done when you run the 
DAPP_NAME=<dapp>  docker compose -f ./deploy-testnet.yml up

To add the validators you should add the parameter --validators with the following value (cartesi insfrastructure validador address) to the create command of the deployer service
0x18930e8a66a1DbE21D00581216789AAB7460Afd0

Using this file as a base https://github.com/cartesi/rollups-examples/blob/5f7d0f991b00a281a8a4c7b092643cc917682c4e/deploy-testnet.yml#L25 you should add this line to the list
        "--validators","0x18930e8a66a1DbE21D00581216789AAB7460Afd0"

We are working on the rollups-deployment docs to add this note. 
GitHub
[rollups-examples/deploy-testnet.yml at 5f7d0f991b00a281a8a4c7b09264...](https://github.com/cartesi/rollups-examples/blob/5f7d0f991b00a281a8a4c7b092643cc917682c4e/deploy-testnet.yml)
Cartesi Rollups Examples. Contribute to cartesi/rollups-examples development by creating an account on GitHub.
rollups-examples/deploy-testnet.yml at 5f7d0f991b00a281a8a4c7b09264...

**Review by endersonmaia — APPROVED** [review]
Please, give it a try on the `/graphsql` and `/inspect` paths for the following URLs.

- `https://0xa17be28f84c89474831261854686a6357b7b9c1e.goerli.rollups.staging.cartesi.io`
- `https://solana-adapter.goerli.rollups.staging.cartesi.io`

**Comment by fabiooshiro** [comment]
Ok!

**Comment by fabiooshiro** [comment]
https://0xa17be28f84c89474831261854686a6357b7b9c1e.goerli.rollups.staging.cartesi.io - ok
https://solana-adapter.goerli.rollups.staging.cartesi.io - ok

**Review by endersonmaia — APPROVED** [review]

**Pull request merged**
